### PR TITLE
Add support for VTK 8.1

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@mleotta, it would be great if you can test this if you get a chance... @dstoup I tried to replicate your 8.0 patches but have not tested.

**Comment by mwoehlke-kitware** [comment]
I also left support for 6.2 for now since ripping it out has implications for OpenCV 2.x, and it was easier to just leave it than to clean it up properly. However, I added notes that we should drop both at the same time.

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
You  should rebase this branch onto release to bring in the qt-moc-patch branch. It should eliminate the need to keep this VTK patch.

**Comment by dstoup** [comment]
Jenkins test this please

**Pull request merged**
