### PR TITLE
Add GDAL dependency on libxml2

### PR DESCRIPTION
**Pull request by mleotta**
This change seems to fix my issue on macOS.  It seem like it might be relevant on other platforms too.

### CODE REVIEW

**Comment by Cookt2** [comment]
Do we want to target release with this fix?

**Comment by mleotta** [comment]
I suppose the release branch makes sense for this.  I will rebase it (and add a release note).  But it might make sense to let the current CI builds finish just to confirm that this is not problematic on master.

**Comment by dstoup** [comment]
Looks like the Windows dashboard went down at some point. Restarting it now and will run that dashboard and merge.

**Comment by dstoup** [comment]
I'm just rerunning the dashboard to test the build_kwiver post task to make sure it's fixed now. I will merge soon.

**Pull request merged**
