### PR TITLE
Add VTK 9.1

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
@mleotta Please review.

**Review by mleotta — APPROVED** [review]
Looks okay to me

**Comment by mleotta** [comment]
@danlipsa Can you add a release note to `master.txt` indicating that the option for VTK 9.1 has been added?

@dstoup do we need to make a temporary commit that makes VTK 9.1 the default to run it through dashboards?  Or can we merge this as long as the builds succeed with the current default, which is not 9.1?

**Comment by danlipsa** [comment]
@mleotta Do you mean Doc/release.txt?

**Comment by mleotta** [comment]
@danlipsa it should be `Doc/release-notes/master.txt`, not `release.txt` and should say something like "Added option to use VTK 9.1".

**Comment by danlipsa** [comment]
@mleotta An unrelated comment on VTK. If VTK operations are slow, some of them can be sped-up by compiling VTK using VTK_SMP_IMPLEMENTATION_TYPE=STDThread. Right now it is Sequential.
Other available options include TBB and OpenMP but these require external libraries.

**Comment by mleotta** [comment]
@danlipsa We use OpenMP in KWIVER.  I don't think that requires installing anything else if you have the appropriate compilers (I think we had trouble with it on Apple).  Is this option only supported for VTK 9.0 or 9.1 or older versions too?  Would you recommend OpenMP over STDThread if OpenMP is available?

**Comment by danlipsa** [comment]
We use OpenMP for non-intel HPC machines. STDThread backend is the newest, so I think OpenMP is a safer bet.

**Pull request merged**
