### PR TITLE
Add PDAL

### PR DESCRIPTION
**Pull request by mleotta**
I need to add PDAL for point cloud I/O support (e.g. LAS files).  I haven't been able to get this to work yet.  I'm getting linking errors.  I could use some help.

### CODE REVIEW

**Comment by Cookt2** [comment]
Linux build failure is not related to this branch. Running the dashboards again.

**Comment by Cookt2** [comment]
Jenkins test this please

**Comment by mleotta** [comment]
I was able to work around the Linux error locally by setting LD_LIBRARY_PATH to the Fletch install/libs. I'm not sure the right way to fix this in CMake.  It may actually be an error in how we build GDAL.  The GDAL library does not have a path to png.

**Comment by Cookt2** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
I have found GDAL a bit flaky as well about its treatment of internal packages for its build. In CMake we usually do something like, e.g. in GDAL

    set(env ${CMAKE_COMMAND} -E env)
    set(env_var LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${fletch_BUILD_INSTALL_PREFIX}/lib)
    set(GDAL_CONFIGURE_COMMAND ${env} ${env_var} ${GDAL_CONFIGURE_COMMAND})

which works for Linux. There is likely a better way to handle this, but that's what we've done in the past.

**Comment by dstoup** [comment]
Otherwise, I think the code looks good.

**Comment by Cookt2** [comment]
Jenkins test this please

**Comment by Cookt2** [comment]
There are errors when PDAL is built without GEOS enabled. GEOS should be added as a required dependency for PDAL. I did that here: https://github.com/Kitware/fletch/commit/9bd1f538a326dbe84622d62014d7cfadfdf8e06f

I'm currently looking into why Windows is not happy with this branch.

**Comment by Cookt2** [comment]
From PDAL configure step:
```
-- The following REQUIRED packages have been found:

 * GDAL (required version >= 1.9.0)
   Provides general purpose raster, vector, and reference system support
 * GEOS (required version >= 3.3)
   Provides general purpose geometry support
 * GeoTIFF
 * ZLIB
   Compression support in BPF
 * Threads, The thread library of the system
```

**Comment by mleotta** [comment]
The Windows builds seem to have errors that are not related to this branch, and the non-GPU Windows machines did not re-run after the latest changes.

**Comment by Cookt2** [comment]
Jenkins test this please

**Comment by Cookt2** [comment]
I've created #500 that addresses some issues I had with this branch.

**Comment by mleotta** [comment]
Can this be merged now?  If not, what changes are needed?

**Comment by Cookt2** [comment]
This looks good to me, the linuxGPU failures aren't related to this branch.

**Pull request merged**
