### PR TITLE
Fix OpenCV Python with Win32 Debug builds

### PR DESCRIPTION
**Pull request by mleotta**
This fix works and is probably good enough for us.  A slightly better approach would be to use CMake to detect if the Python Debug libraries are found and only employ this hack if they are not.  I may try that approach in the future and push it upstream to OpenCV.

### CODE REVIEW

**Comment by dstoup** [comment]
Do we need to patch this for other versions of OpenCV?

**Comment by mleotta** [comment]
Possibly, but I don't have time to test that.

**Comment by mleotta** [comment]
A side note on this PR:  Once this lands in `release`, we need to be careful about merging `release` into `master`.  The new `cv2.cpp` added here in `Patches\OpenCV3\` needs to move to `Patches\OpenCV\3.1.0\` on `master`.  By default this will file will merge without conflict and not properly relocate causing `master` to break.  The file needs to be manually moved when merged into `master`.

**Comment by dstoup** [comment]
Sounds good. I can try picking at the others as the problem arises. At least we have the template for the fix.

**Comment by mleotta** [comment]
@dstoup This branch was to fix Windows builds and it works on all my Windows configurations.  The Jenkins failure appears to be due to that Qt issue you had after upgrading the compiler.  Has that been fixed?  Can we just merge this PR?  Do you want to re-test, and if so, do I need to rebase to get your fix for Qt?

**Comment by dstoup** [comment]
The Qt PR merged. I don't think we will need a rebase. I would say, go
ahead and merge. If you can't, I will when I get to the hotel.

**Pull request merged**
