### PR TITLE
Add pybind11 patches

### PR DESCRIPTION
**Pull request by KyleFromKitware**
This adds a set of patches to pybind11 that fix pybind/pybind11#1276 (the changes I've made can be seen in pybind/pybind11#1286)

### CODE REVIEW

**Comment by dstoup** [comment]
A comment about patch branches in general. I prefer 2 commits. One which pushes the original files and a second which applies the patch. That will allow reviewers to see what's actually being changed.

**Comment by KyleFromKitware** [comment]
Like this?

**Comment by dstoup** [comment]
Yes, thank you :)

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by KyleFromKitware** [comment]
The builds are failing:

```
CMake Error at CMake/External_Tensorflow.cmake:4 (message):
  Error: A build with Python is required for building Tensorflow
```

Is Jenkins not configured for Python? Does this usually happen?

**Comment by dstoup** [comment]
FYI, this is more for Dawkins than anyone, but if there are useful changes being made, I would prefer they go into master, not some frankenbranch which will not merge. 

Are these changes useful for pybind11 in general?

**Comment by hughed2** [comment]
Kyle, do you want to push that into viame/master or plain master? Jenkins is configured for master, if viame/master needs anything different I wouldn't expect it to work.

**Comment by dstoup** [comment]
Jenkins is not configured with python and any packages which are added need to assume it can be turned on or off.

**Comment by dstoup** [comment]
@hughed2 this branch cannot go into master, it was taken from viame/master.

**Pull request closed without merging**
