### PR TITLE
Make a patched version of pybind11 2.10.3 available in Fletch

### PR DESCRIPTION
**Pull request by chetnieter**
PR to test if pybind11 version 2.9.2 will break KWIVER

### CODE REVIEW

**Comment by mattdawkins** [comment]
Similar to https://github.com/Kitware/fletch/pull/705/files, abandon that one if this goes in

**Comment by chetnieter** [comment]
jenkins test this please

**Comment by chetnieter** [comment]
jenkins test this please

**Comment by chetnieter** [comment]
jenkins test this please

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by chetnieter** [comment]
jenkins test this please

**Comment by chetnieter** [comment]
jenkins test this please

**Pull request merged**
