### PR TITLE
Make opencv shared build dependent on fletch shared build

### PR DESCRIPTION
**Pull request by as6520**
This PR updates the opencv build to support static build that is used for kwiver wheel.

### CODE REVIEW

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
Here the Windows errors are real:

https://open.cdash.org/viewBuildError.php?buildid=6739741

**Comment by as6520** [comment]
Thanks for the info, I will look into it

**Comment by dstoup** [comment]
Jenkins test this please

**Review by dstoup — APPROVED** [review]

**Pull request merged**
