### PR TITLE
Enable gdal python

### PR DESCRIPTION
**Pull request by dstoup**
Enable GDAL python when fletch_BUILD_WITH_PYTHON is enabled

### CODE REVIEW

**Comment by dstoup** [comment]
@william.hicks

**Comment by dstoup** [comment]
@wphicks

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by wphicks** [comment]
LGTM once dashboard build is fixed.

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
Jenkins test this please

**Pull request merged**
