### PR TITLE
Update qtExtensions

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Update to latest qtExtensions, which adds `qtUtil::setIconTheme` and fixes some warnings.

### CODE REVIEW

**Comment by dstoup** [comment]
Just FYI, here is the error message from the Linux GPU dash...

[ 69%] Building CXX object CMakeFiles/qtExtensions.dir/sax/qtSaxNodes/mnt/ssd/data/Dashboards/jenkins/workspace/FletchLinuxGPUPR/build/build/src/qtExtensions/dom/qtDom.cpp: In function ‘QList<QDomElement> qtDom::findElements(const QDomNode&, const QString&)’:
/mnt/ssd/data/Dashboards/jenkins/workspace/FletchLinuxGPUPR/build/build/src/qtExtensions/dom/qtDom.cpp:53:57: error: ‘SkipEmptyParts’ is not a member of ‘Qt’
   const QStringList selectors = selector.split(' ', Qt::SkipEmptyParts);
                                                         ^~~~~~~~~~~~~~
.cpp.o
[ 70%] Building CXX object CMakeFiles/qtExtensions.dir/sax/qtSaxTraversal.cpp.o
[ 71%] Building CXX object CMakeFiles/qtExtensions.dir/sax/qtSaxWriter.cpp.o
CMakeFiles/qtExtensions.dir/build.make:874: recipe for target 'CMakeFiles/qtExtensions.dir/dom/qtDom.cpp.o' failed
make[5]: *** [CMakeFiles/qtExtensions.dir/dom/qtDom.cpp.o] Error 1
types.h

**Comment by mwoehlke-kitware** [comment]
> error: ‘SkipEmptyParts’ is not a member of ‘Qt’

Oy, that's a horrible change to have made in a minor release :sob:.

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by mwoehlke-kitware** [comment]
@dstoup, is this still broken? Can you post / point me to the issues?

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
The problem I see now is that your call
`if(fletch_ENABLE_qtExtensions)`
needs to change to 
`if(fletch_ENABLE_qtExtensions OR fletch_ENABLE_ALL_PACKAGES)`
otherwise we skip over everything.

**Comment by dstoup** [comment]
Looks good to me ... thank you!

**Pull request merged**
