### PR TITLE
Set VTK 8.2 as default

### PR DESCRIPTION
**Pull request by mleotta**
This branch sets the default version of VTK to 8.2.  This allows us to test #521, which adds 8.2 but does not make it the default.  If CI passes on this branch we should merge #521 and then consider merging this branch as well.

### CODE REVIEW

**Comment by mleotta** [comment]
I saw the Windows build issue too.  It actually builds fine if you restart the build, but this is still a bug with the CMake in VTK.  I'm working on a fix.

**Comment by mleotta** [comment]
I made a small patch for VTK for Windows builds (I also pushed it upstream to VTK).  The dashboard is now green with VTK 8.2 as the default.  Can we merge #521 now to add 8.2 and then revisit this branch to make it default later?

**Comment by mleotta** [comment]
@mwoehlke-kitware, it would be very helpful for me (and my CI builds) to have VTK 8.2 used by default in Fletch.  8.2 is building cleanly on the CI machines.  If 8.2 is the default it will fix my broken TeleSculptor CI builds that require 8.2 and build against the nightly Fletch binaries.

Do you have ViViA CI/Dashboard builds that also make use of the nightly Fletch binaries?  If 8.2 is the default can you configure your builds to use 8.0 if needed?  Can you test if ViViA happens to work with 8.2?

**Comment by mwoehlke-kitware** [comment]
I think @dstoup or @RustyBlue would be more appropriate to answer that...

ViViA will *most certainly not* work with 8.2, as there is no OpenGL [legacy] back-end in 8.2. I also don't know what, if any, CMake changes are needed for the new module system, assuming that is even present in 8.2 (I don't know if it is or not).

**Comment by mleotta** [comment]
My opinion is that we should merge this change because it will fix the TeleSculptor CI builds that require VTK 8.2 in nightly builds of Fletch.  My understanding is that ViViA does not use the default Fletch for CI.  ViViA can still configure Fletch to use VTK 8.0 for now, but making 8.2 the default will add incentive to update ViViA when someone is available to do that work.

@RustyBlue @dstoup @mwoehlke-kitware Thoughts? Objections?

**Comment by RustyBlue** [comment]
No objection to making 8.2 the default.

**Comment by mleotta** [comment]
Is there a way to re-run the Mac build?  The errors look unrelated to this change and it passed previously.

**Comment by dstoup** [comment]
The easiest way to rerun a PR is to run them all.

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by mleotta** [comment]
@dstoup CI builds seem to be intermittently failing on unrelated things.  Can we merge this, or do we need to try running the builds again?

**Pull request merged**
