### PR TITLE
Add x264 support

### PR DESCRIPTION
**Pull request by daniel-riehm**
Add the x264 library (for encoding H.264 video) as a fletch module and hook it up to FFmpeg. I have confirmed that this works (compiles AND produces valid H.264 video in KWIVER) on my Linux machine. However, since we don't build FFmpeg from source on Windows, instead downloading pre-built binaries, we can't hook x264 up to it in fletch. From my understanding, we would need to create new versions of these binaries with x264 support enabled. Probably repeat the process for x265 if / when we ever get to it. @chetnieter - do you have any comment on this?

x264 is under a GPL license. Don't know if that matters for anything.

### CODE REVIEW

**Comment by chetnieter** [comment]
We did not create the pre-built windows binaries hosted on data.kitware.com, they were pulled from other sites on the web. The latest 4.4.1 builds came from https://www.gyan.dev/ffmpeg/builds/. @mleotta may know more about that.

**Comment by mleotta** [comment]
All I know is that years ago we decided that it was far to tricky to build ffmpeg on Windows in Fletch.  It does not use CMake and I think it will not build with Visual Studio.  So the solution was to pull down pre-built binaries.  It's possible that could manually make and host our own ffmpeg windows binaries with the options and/or patches that we need, but we haven't don't that before.

**Comment by mleotta** [comment]
jenkins please test this

**Comment by mleotta** [comment]
jenkins please test this

**Comment by mleotta** [comment]
jenkins test this please

**Comment by mleotta** [comment]
jenkins test this please

**Comment by mleotta** [comment]
jenkins test this please

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by mleotta** [comment]
@dstoup could you find some time to review this PR?

**Comment by dstoup** [comment]
t think the code looks ok. There is a Windows build issue ,,,

https://open.cdash.org/viewBuildError.php?buildid=8004007

Not sure what is causing it yet though. Possible that we need config changes on the dashboard to make this all work? If you need, you can log in to squornshellous. The build is here: D:/workspace/FletchWindowsPR/build and I think you can use the standard username/password, otherwiser it should be on the domain. Let me know if you need help with access.

There is also an error on the linux GPU machine but that looks like a system config issue with the compiler.
https://open.cdash.org/build/8003257/configure

I can try looking into that today as well

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
The Linux GPU machine had a fixed path to gcc 6 but is using gcc 7. Fixed those config issues for a rerun

**Review by dstoup — APPROVED** [review]
Looks like the Linux GPU is still failing a configuration. PR looks good to me. Merge when ready.

**Pull request merged**
