### PR TITLE
Upgrade yaml-cpp to 0.7.0

### PR DESCRIPTION
**Pull request by daniel-riehm**
Similar to #690, but this version shouldn't have the same MSVC problem.

### CODE REVIEW

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by daniel-riehm** [comment]
jenkins test this please

**Review by dstoup — APPROVED** [review]
Code looks good. Approval dependent on dashboard success.

**Comment by daniel-riehm** [comment]
There are other underlying dashboard issues which will prevent this PR from ever passing CI on its own. #709 demonstrates that CI can "pass" in combination with other PRs.

**Pull request merged**
