### PR TITLE
Add patch to write KLV descriptors

### PR DESCRIPTION
**Pull request by daniel-riehm**
Add a patch modifying FFmpeg to write metadata descriptor structures when writing synchronous KLV to a MPEG-TS file. This is to be in compliance with MISB ST1402.

### CODE REVIEW

**Comment by mleotta** [comment]
It's a bit of a pain, but since CMake can't portably do actually patching and we are overwriting complete files, we recommend that patches added to Fletch are made in at least 2 commits.  The first commit should add the file to be patched in its unchanged form.  The second commit should be the patch to this file.  This way we can see what changes were actually made by reviewing the git history.

**Comment by daniel-riehm** [comment]
> It's a bit of a pain, but since CMake can't portably do actually patching and we are overwriting complete files, we recommend that patches added to Fletch are made in at least 2 commits. The first commit should add the file to be patched in its unchanged form. The second commit should be the patch to this file. This way we can see what changes were actually made by reviewing the git history.

Done

**Review by mleotta — APPROVED** [review]
This change looks okay to me.  Please also push upstream to see if we can get this change accepted into FFMPEG.

One issue we will face is that any FFmpeg patches will not impact our Windows builds because we use pre-built Windows binaries.  This is all the more reason to get these changes pushed upstream.

It would also be good to make a release note about this change.  And since 4.4.1 is not the current default, we might want to make a temporary commit that makes 4.4.1 the default just to test that CI can actually build this.

**Comment by daniel-riehm** [comment]
> Please also push upstream to see if we can get this change accepted into FFMPEG.

I have done so, though FFmpeg uses an odd mailing-list system for code review instead of GitHub PRs, so hopefully I submitted it correctly.

> It would also be good to make a release note about this change. And since 4.4.1 is not the current default, we might want to make a temporary commit that makes 4.4.1 the default just to test that CI can actually build this.

Is this in fletch or kwiver?

**Comment by mleotta** [comment]
I was suggesting a release note and temporary commit to trigger CI here in Fletch, not KWIVER.

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by mleotta** [comment]
jenkins test this please

**Comment by daniel-riehm** [comment]
The CI is failing only because the mvg tracking test is timing out. Is this something I need to worry about?

**Pull request merged**
