### PR TITLE
Update release versioning in relevant files

### PR DESCRIPTION
**Pull request by johnwparent**
Update release info and versioning for upcoming patch release

Fresh release.txt
Updated v1.4.1 release notes

### CODE REVIEW

**Comment by dstoup** [comment]
I think this looks right. Will wait for Matt before merging.

**Review by mleotta — APPROVED** [review]
I approve.  I just want to make sure we are tracking #634 and making a decision on that before release.

**Comment by johnwparent** [comment]
I believe that we had decided to go forward with the patch release and make an effort to incorporate #634 into the upcoming minor release.

**Comment by mleotta** [comment]
That's okay by me, but #634 is currently tagged for `patch release` and I think @dstoup wanted to get it landed.

**Review by mleotta — APPROVED** [review]
Looks good.  Are we ready to make the release?

**Comment by johnwparent** [comment]
It looks like all outstanding PRs can be incorporated into the minor release, and the draft is updated, as long as @dstoup agrees, it's all good to go on my end.

**Review by dstoup — APPROVED** [review]

**Pull request merged**
