### PR TITLE
Update VTK 8.2-pre to 8.2 and remove 8.1

### PR DESCRIPTION
**Pull request by mleotta**
Update VTK to the latest version, 8.2.  MAP-Tk / TeleSculptor requires this.  We were using a pre-release of 8.2 before it was officially released to get the required features.

Also remove older version 8.1.  Ultimately we should removed 8.0 as well, but I recall @mwoehlke-kitware had some issue with newer VTK that has not been worked around and requires 8.0.  @mwoehlke-kitware, is that still the case?

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
> Ultimately we should removed 8.0 as well, but I recall @mwoehlke-kitware had some issue with newer VTK that has not been worked around and requires 8.0. @mwoehlke-kitware, is that still the case?

Yes; ViViA still requires the old OpenGL back-end. (IIRC this is at least partly because OpenGL2 is broken in 8.0. Using 8.1 is not an option because VTK broke the modules build API; I'm not sure if the new API is in 8.2 or not.)

Relatedly, I'd love to get rid of 6.2...

**Comment by mleotta** [comment]
@mwoehlke-kitware, when you get a chance, let us know if 8.2 resolves your issues with ViViA.

I'm also in favor of getting rid if 6.2.  I was under the impression that we still had some legacy code that need this.  If that's not the case, we should get rid of 6.2 too.

**Comment by mwoehlke-kitware** [comment]
I'm not aware of any KW projects that still rely on VTK < 8.0. The comment says something about "OpenCV < 3.2", so I assume it is needed for OpenCV 2.x. (I wouldn't know who, if anyone, still needs that.)

**Comment by dstoup** [comment]
FWIW, The Clang build is failing for fletch in general, not related to this (or any other) PR. Boost and a few other packages are unhappy with Clang on CentOS 7.

**Comment by mleotta** [comment]
@dstoup 
#523 CI builds are green.  #523 makes VTK 8.2 the default for testing.  So can we merge this branch now to put the option in?

**Pull request merged**
