### PR TITLE
Add pybind11 patches

### PR DESCRIPTION
**Pull request by KyleFromKitware**
This adds a set of patches to pybind11 that fix pybind/pybind11#1276 (the changes I've made can be seen in pybind/pybind11#1286)

### CODE REVIEW

**Comment by hughed2** [comment]
LGTM

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
Looks good to me too. I will merge once the dashboard cycles.

**Comment by KyleFromKitware** [comment]
Closed because I am going to take a new approach that doesn't involve patching pybind11.

**Pull request closed without merging**
