### PR TITLE
Update qtExtensions

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Update to latest qtExtensions, which brings a fix for Qt5 and some additional convenience features.

### CODE REVIEW

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
I've isolated what snippets I could from the Linux failure. Not sure if they will be of use, but just in case, here they are.

[ 19%] Building CXX object CMakeFiles/qtExtensions.dir/util/qtAbstractSetting.cpp.o
[ 20%] Building CXX object CMakeFiles/qtExtensions.dir/util/qtActionFactory.cpp.o
[ 21%] Building CXX object CMakeFiles/qtExtensions.dir/util/qtActionManager.cpp.o
[ 22%] Building CXX object CMakeFiles/qtExtensions.dir/util/qtActionPriorityList.cpp.o
[ 23%] Building CXX object CMakeFiles/qtExtensions.dir/util/qtColorScheme.cpp.o
[ 24%] Building CXX object CMakeFiles/qtExtensions.dir/util/qtColorUtil.cpp.o
[ 25%] Building CXX object CMakeFiles/qtExtensions.dir/util/qtIn file included from /home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/qtActionManager.h:14:0,
                 from /home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/qtActionManager.cpp:7:
/home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/qtActionManager.cpp: In member function 'void qtActionManager::reloadActions(QSettings&) const':
/home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/qtActionManager.cpp:143:58: error: call of overloaded 'qtEnumerate(const StaticActionMap&)' is ambiguous
   foreach (auto const& iter, qtEnumerate(d->staticActions))
                                                          ^
/home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/../core/qtGlobal.h:466:52: note: in definition of macro 'QTE_FOREACH'
 #  define QTE_FOREACH(decl, container) for (decl : container)
                                                    ^
/home/kitware/jenkins/wDockController.cpp.o
[ 26%] Building CXX object CMakeFiles/qtExtensions.dir/util/qtDockControllerPrivate.cpp.o
[ 27%] Building CXX object CMakeFiles/qtExtensions.dir/util/qtGradient.cpp.o
orkspace/FletchLinuxPR/build/build/src/qtExtensions/util/qtActionManager.cpp:143:3: note: in expansion of macro 'foreach'
   foreach (auto const& iter, qtEnumerate(d->staticActions))
   ^
/home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/qtActionManager.cpp:143:58: note: candidates are:
   foreach (auto const& iter, qtEnumerate(d->staticActions))
                                                          ^
/home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/../core/qtGlobal.h:466:52: note: in definition of macro 'QTE_FOREACH'
 #  define QTE_FOREACH(decl, container) for (decl : container)
                                                    ^
/home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/qtActionManager.cpp:143:3: note: in expansion of macro 'foreach'
   foreach (auto const& iter, qtEnumerate(d->staticActions))
   ^
In file included from /home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/qtActionManager.cpp:12:0:
/home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/../core/qtEnumerate.h:142:27: note: qtEnumerator<const Range> qtEnumerate(Range&) [with Range = const QHash<QAction*, QString>]
 qtEnumerator<Range const> qtEnumerate(Range& range)
                           ^
/home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/../core/qtEnumerate.h:185:28: note: void qtEnumerate(T&&) [with T = const QHash<QAction*, QString>&] <deleted>
 template <typename T> void qtEnumerate(T&&) = delete;
                            ^
make[5]: *** [CMakeFiles/qtExtensions.dir/util/qtActionManager.cpp.o] Error 1
[ 28%] Building CXX object CMakeFiles/qtExtensions.dir/util/qtJson.cpp.o
[ 29%] Building CXX object CMakeFiles/qtExtensions.dir/util/qtNaturalSort.cpp.o
[ 30%] Building CXX object CMakeFiles/qtExtensions.dir/util/qtPrioritizedMenuProxy.cpp.o
[ 31%] Building CXX object CMakeFiles/qtExtensions.dir/util/qtPrioritizedToolBarProxy.cpp.o
[ 32%] Building CXX object CMakeFiles/qtExtensions.dir/util/qtProcess.cpp.o
[ 34%] Building CXX object CMakeFiles/qtExtensions.dir/util/qtScopedSettingsGroup.cpp.o
In file included from /home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/qtJson.cpp:10:0:
/home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/qtJson.cpp: In function 'qtJson::JsonData qtJson::encode(const Object&)':
/home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/qtJson.cpp:96:47: error: call of overloaded 'qtEnumerate(const Object&)' is ambiguous
   foreach (auto const iter, qtEnumerate(object))
                                               ^
/home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/../core/qtGlobal.h:466:52: note: in definition of macro 'QTE_FOREACH'
 #  define QTE_FOREACH(decl, container) for (decl : container)
                                                    ^
/home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/qtJson.cpp:96:3: note: in expansion of macro 'foreach'
   foreach (auto const iter, qtEnumerate(object))
   ^
/home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/qtJson.cpp:96:47: note: candidates are:
   foreach (auto const iter, qtEnumerate(object))
                                               ^
/home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/../core/qtGlobal.h:466:52: note: in definition of macro 'QTE_FOREACH'
 #  define QTE_FOREACH(decl, container) for (decl : container)
                                                    ^
/home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/qtJson.cpp:96:3: note: in expansion of macro 'foreach'
   foreach (auto const iter, qtEnumerate(object))
   ^
In file included from /home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/qtJson.cpp:9:0:
/home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/../core/qtEnumerate.h:142:27: note: qtEnumerator<const Range> qtEnumerate(Range&) [with Range = const QMap<QString, QVariant>]
 qtEnumerator<Range const> qtEnumerate(Range& range)
                           ^
/home/kitware/jenkins/workspace/FletchLinuxPR/build/build/src/qtExtensions/util/../core/qtEnumerate.h:185:28: note: void qtEnumerate(T&&) [with T = const QMap<QString, QVariant>&] <deleted>
 template <typename T> void qtEnumerate(T&&) = delete;
                            ^
make[5]: *** [CMakeFiles/qtExtensions.dir/util/qtJson.cpp.o] Error 1
rming Test HAVE_CXX_WNO_COMMENT - Success
-- Performing Test HAVE_C_WNO_COMMENT

...............

[ 74%] Building CXX object CMakeFiles/qtExtensions.dir/qtExtensions_autogen/mocs_compilation.cpp.o
make[4]: *** [CMakeFiles/qtExtensions.dir/all] Error 2
make[4]: Target `all' not remade because of errors.
make[3]: *** [all] Error 2
make[3]: Target `default_target' not remade because of errors.
make[2]: *** [build/src/qtExtensions-stamp/qtExtensions-build] Error 2
make[2]: Target `CMakeFiles/qtExtensions.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/qtExtensions.dir/all] Error 2
 GLX_DEFINES_TYPE_GLXextFuncPtr_AS_EMPTY - Failed

**Comment by mwoehlke-kitware** [comment]
Joy. Not only is that a compiler bug, it's one I've seen... ah...

...[before](https://github.com/Kitware/qtextensions/blob/022770080763b9fccd4678162ab9bf9d9b006ed3/core/qtGet.h#L44-L55).
\*headdesk\*

https://github.com/Kitware/qtextensions/pull/16

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
See Windows errors. Doesn't make sense on quick glance because we should be building with C++11 for every package.

**Comment by mwoehlke-kitware** [comment]
Uh... MSVC does not define __cplusplus to at least 201103? What version of MSVC?

**Comment by mwoehlke-kitware** [comment]
> Uh... MSVC does not define __cplusplus to at least 201103? What version of MSVC?

To answer my own question... no it doesn't, [prior to `_MSC_VER==1914`](https://blogs.msdn.microsoft.com/vcblog/2018/04/09/msvc-now-correctly-reports-__cplusplus/). Ugh. (And even then, needs `/Zc:__cplusplus`.)

Note: I have updated qtExtensions now, but it will want that compile flag...

**Comment by mwoehlke-kitware** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
Jenkins test this please

**Pull request merged**
