### PR TITLE
Fix top-level setting of CMAKE_INSTALL_LIBDIR

### PR DESCRIPTION
**Pull request by KyleFromKitware**
This variable is supposed to be relative to the installation prefix,
rather than absolute. This change sets it to a relative path.

### CODE REVIEW

**Comment by mleotta** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
I think this should work well. It should always be pointing the the install/lib dir. Looks good to me pending dashboard runs.

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
It seems that with this change, during the OpenCV build FFmpeg is not able to find itself. 

 [100%] Linking CXX executable ../../bin/opencv_interactive-calibration
/usr/bin/ld: warning: libswresample.so.1, needed by //var/jenkins_home/jobs/FletchLinuxPR/workspace/build/install/lib/libavcodec.so.56, not found (try using -rpath or -rpath-link)

There is a patch I've used for other OpenCV executables. I will investigate that here.

**Comment by dstoup** [comment]
I have made a PR for this branch which should fix the failures.

https://github.com/KyleFromKitware/fletch/pull/1

**Comment by KyleFromKitware** [comment]
@dstoup I have cherry-picked your change onto this branch. Go ahead and test again.

**Comment by dstoup** [comment]
Perfect, thanks Kyle!

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by KyleFromKitware** [comment]
Take 3

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
> Take 3

It just keeps getting better!

**Pull request merged**
