### PR TITLE
Add VTK 8.0 patches for vtkSeedWidget changes from release branch

### PR DESCRIPTION
**Pull request by sankhesh**

### CODE REVIEW

**Comment by sankhesh** [comment]
@mleotta @dstoup Please review

**Comment by dstoup** [comment]
Does this code already exist on release? If so, it should already be in master (or will be soon) since I merge release back in to master as bugs are fixed.

**Comment by dstoup** [comment]
Sorry, I can see that it isn't. The comment confused me.

The only critique I have is that, when patching fletch, I prefer if it's done in 2 commits. The first to add the files and the second to apply the change. That way we can see what was actually changed.

If it's not too difficult, could you do that? Otherwise, it's not a huge deal, just something to remember for the future.

**Comment by sankhesh** [comment]
@dstoup The code in the patch exists on the VTK release branch (which is beyond v8.1.1 i.e. the latest tag) as well as VTK master branch. Since it is beyond the latest tag, it doesn't exist in the VTK code that fletch pulls.

**Comment by dstoup** [comment]
@sankhesh sounds good. Thanks!

**Comment by sankhesh** [comment]
> The only critique I have is that, when patching fletch, I prefer if it's done in 2 commits. The first to add the files and the second to apply the change. That way we can see what was actually changed.

That makes sense. I can do that.

Although, is there a way to just pull in and apply the two commits I mention in [Patch.cmake](https://github.com/Kitware/fletch/pull/420/files#diff-6982d83b8b5a1dc9063a3440e9b32b29R9) directly without having to copy the whole source file?

**Comment by sankhesh** [comment]
Something along the lines of:

```
set(PATCH_COMMAND 
 ${GIT_EXECUTABLE} apply <commit1> <commit2>
)
```

**Comment by dstoup** [comment]
I like that.

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
Looks like isla-nublar is unhappy with this change.

**Comment by sankhesh** [comment]
@dstoup Could you please run jenkins on this again? I don't think it likes me :frowning_face:

**Comment by hughed2** [comment]
Jenkins test this please

**Comment by hughed2** [comment]
To prevent random people from tying up our dashboard machines, only certain people can trigger builds. Unfortunately, the github Kitware group is barely used, so people are kind of added ad hoc individually instead.

**Comment by mleotta** [comment]
@dstoup does this look okay to merge?  It looks like the only failure is on proteus and is unrelated to this change (maybe out of disk space?).

**Comment by dstoup** [comment]
It looks fine to me. I would like to try the linux build once more. I saw this message earlier today followed by another successful build.

**Comment by dstoup** [comment]
Jenkins test this please

**Pull request merged**
