### PR TITLE
Patch PDAL PlyReader

### PR DESCRIPTION
**Pull request by daniel-riehm**
Change `std::istream::streampos` to `std::streampos`, since the former doesn't exist in some modern compilers.

### CODE REVIEW

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by daniel-riehm** [comment]
jenkins test this please

**Review by dstoup — APPROVED** [review]
Approval dependent on dashboard success. I will take a look at the errors to see whether it's code related or infrastructure.

**Comment by dstoup** [comment]
The LinuxGPU failure is known from the last PR I reviewed.

MAC and Windows are odd errors I haven't seen before. They don't seem particular to this PR but something is wrong and I'm not sure where is came in.

https://open.cdash.org/index.php?project=Fletch

**Comment by daniel-riehm** [comment]
jenkins test this please

**Comment by daniel-riehm** [comment]
There are other underlying dashboard issues which will prevent this PR from ever passing CI on its own. #709 demonstrates that CI can "pass" in combination with other PRs.

**Pull request merged**
