### PR TITLE
Versioned VTK

### PR DESCRIPTION
**Pull request by Erotemic**
This PR exposes a variable `VTK_SELECT_VERSION` to select a version of VTK to build and updates the patches of VTK to use the versioning system proposed in #173. 

The default version of VTK is still 6.2, but the option now exists to set version 7.1.1 or version 8.0.

### CODE REVIEW

**Comment by mleotta** [comment]
@RustyBlue, it looks like @Erotemic beat me too this, and his branch is more general than mine.  It supports changing the version.  You should be able to use this to test out VTK 8.0 for VIVIA.  As we discussed, the upgrade was fairly seamless for MAP-Tk.

**Comment by mleotta** [comment]
@Erotemic I would drop the 7.1.1 unless there is some issue with 8.0 that requires us to fall back to an earlier release.  Let's keep 6.2 and 8.0 until we can confirm that we can drop 6.2.

**Comment by Erotemic** [comment]
I have 7.1.1 in there because I'm not sure that OpenCV supports 8.0 yet. I'll drop it if I find out it does.

**Comment by mleotta** [comment]
I didn't know OpenCV even used VTK :)

I'm not sure that ever use VTK via OpenCV, so that might not be a good driving factor.  We might be able to turn off VTK use in OpenCV if it's a problem, or patch OpenCV.

**Comment by dstoup** [comment]
I didn't realize VTK was getting passed to OpenCV either. It is quite
likely the we can turn that off until someone clamours to have it.

On Aug 4, 2017 4:22 PM, "Matt Leotta" <notifications@github.com> wrote:

I didn't know OpenCV even used VTK :)

I'm not sure that ever use VTK via OpenCV, so that might not be a good
driving factor. We might be able to turn off VTK use in OpenCV if it's a
problem, or patch OpenCV.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Kitware/fletch/pull/175#issuecomment-320344634>, or mute
the thread

**Comment by Erotemic** [comment]
PR #174 disables the OpenCV option to link to VTK by default. 

I believe the only thing this PR is doing right now is exposing 8.0 as an option (I removed 7.1.1 as an option), while still defaulting to the stable 6.2.

**Comment by mleotta** [comment]
Assuming it doesn't cause any problems, I'm in favor of landing this branch and keeping the default VTK at 6.2.  This will give us some time to test VTK 8.0 with downstream applications that use VTK.  It will make it easier to do that testing by flipping a switch in Fletch to change VTK versions.  Once we are satisfied with VTK 8.0 we can make that the default in a separate PR.  And possibly remove support for VTK 6.2 as well.

**Comment by mleotta** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
The same comment as before, the * Added experimental support for VTK version 8.0' release-note should go in the top section with package update info.

Ready to merge after that.

**Comment by mleotta** [comment]
@dstoup it looks like the release notes updates are in the right section.

**Comment by Erotemic** [comment]
Rebased on master. The release notes should be good now.

**Pull request merged**
