### PR TITLE
Update yaml-cpp to 0.6.0

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Update to a newer release of yaml-cpp. Particularly, this version uses C++11 and removes the dependency on Boost. (It also appears to have the patches we need, allowing us to remove our local patches.)

### CODE REVIEW

**Review by dstoup — APPROVED** [review]

**Comment by dstoup** [comment]
Windows build error:

D:\workspace\FletchWindowsPR\build\build\src\YAMLcpp\include\yaml-cpp/exceptions.h(261): error C3646: '_NOEXCEPT': unknown override specifier [D:\workspace\FletchWindowsPR\build\build\src\YAMLcpp-build\yaml-cpp.vcxproj] [D:\workspace\FletchWindowsPR\build\YAMLcpp.vcxproj]

**Comment by dstoup** [comment]
If you look at  ${YAMLcpp_source}/include/yaml-cpp/exceptions.h and ${YAMLcpp_source}/src/exceptions.cpp you can see the issue.

// This is here for compatibility with older versions of Visual Studio
// which don't support noexcept
#ifdef _MSC_VER
    #define YAML_CPP_NOEXCEPT _NOEXCEPT
#else
    #define YAML_CPP_NOEXCEPT noexcept
#endif

I don't know where _NOEXCEPT is supposed to come from but I'm guessing it's some pre-c++11 MSVC definition. It doesn't appear to be defined though, thus the error. Also not sure how much 'older' MSVC needs to be for that to work, but reducing it to 

#define YAML_CPP_NOEXCEPT noexcept

works just fine on the dashboard machine.

**Comment by mwoehlke-kitware** [comment]
Yeah, it needs a patch reintroduced. Unfortunately I don't know when/if I'll get to it, as it looks like I'm not going to be using fletch after all for the project that needs the newer version.

**Comment by daniel-riehm** [comment]
Closed in favor of #708.

**Pull request closed without merging**
