### PR TITLE
Add Python to PATH for Win32 Qt builds

### PR DESCRIPTION
**Pull request by mleotta**

### CODE REVIEW

**Comment by dstoup** [comment]
Looks good to me. The dashboards won't likely test this branch correctly since they have python on the path on the Window's machine. If you've confirmed that it works, I'm ok with it.

**Comment by mleotta** [comment]
It works for me on my Windows machine.

**Comment by dstoup** [comment]
Looks good to me, but I don't understand the MAC error. Running dashboard again in the hopes that it's a fluke

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by mleotta** [comment]
It looks like the Mac build is okay now and other errors are unrelated.  Can we merge this (and then merge release into master)?

**Comment by dstoup** [comment]
Yes, was just coming to do that.

**Pull request merged**
