### PR TITLE
Add OpenCV 4.7.0 as an option, to support certified dependencies.

### PR DESCRIPTION
**Pull request by aronhelser**

### CODE REVIEW

**Comment by aronhelser** [comment]
@chetnieter Adding OpenCV 4.7

**Comment by daniel-riehm** [comment]
> @daniel-riehm Where do I put new tarballs on data.kitware.com? Your MR didn't include any instructions.

https://data.kitware.com/#collection/591a0dbb8d777f16d01e0cb1/folder/66217e945165b19d36c87fd0

Good point - I'll add instructions to the tarballs file

**Comment by aronhelser** [comment]
Want to add https://github.com/opencv/opencv/archive/4.7.0.zip and http://github.com/opencv/opencv_contrib/archive/4.7.0.zip to that folder, please? I don't have access to upload.

**Comment by daniel-riehm** [comment]
> Want to add https://github.com/opencv/opencv/archive/4.7.0.zip and [http://github.com/opencv/opencv_contrib/archive/4.7.0.zip](https://github.com/opencv/opencv_contrib/archive/4.7.0.zip) to that folder, please? I don't have access to upload.

https://data.kitware.com/api/v1/file/664cd3cf85908871f9b3adb4/download/opencv.${OpenCV_version}.tar.gz
https://data.kitware.com/api/v1/file/664cd3e985908871f9b3adb7/download/opencv-contrib.${OpenCV_version}.zip

**Review by chetnieter — APPROVED** [review]

**Comment by aronhelser** [comment]
I don't have merge permission, so I need someone to push the button.

**Comment by daniel-riehm** [comment]
This breaks the Windows build:
```
  D:/workspace/FletchWindowsPR/build/build/src/FFmpeg/libavdevice/vfwcap.c: In function 'vfw_read_header':
D:/workspace/FletchWindowsPR/build/build/src/FFmpeg/libavdevice/vfwcap.c(331,35): error G15CAB38F: passing argument 1 of 'av_parse_video_size' from incompatible pointer type [-Wincompatible-pointer-types] [D:\workspace\FletchWindowsPR\build\FFmpeg.vcxproj]
    331 |         ret = av_parse_video_size(&bi->bmiHeader.biWidth, &bi->bmiHeader.biHeight, ctx->video_size);
        |                                   ^~~~~~~~~~~~~~~~~~~~~~
        |                                   |
        |                                   LONG * {aka long int *}
  In file included from D:/workspace/FletchWindowsPR/build/build/src/FFmpeg/libavdevice/vfwcap.c:25:
  D:/workspace/FletchWindowsPR/build/build/src/FFmpeg/libavutil/parseutils.h:66:30: note: expected 'int *' but argument is of type 'LONG *' {aka 'long int *'}
     66 | int av_parse_video_size(int *width_ptr, int *height_ptr, const char *str);
        |                         ~~~~~^~~~~~~~~
D:/workspace/FletchWindowsPR/build/build/src/FFmpeg/libavdevice/vfwcap.c(331,59): error G15E9B38F: passing argument 2 of 'av_parse_video_size' from incompatible pointer type [-Wincompatible-pointer-types] [D:\workspace\FletchWindowsPR\build\FFmpeg.vcxproj]
    331 |         ret = av_parse_video_size(&bi->bmiHeader.biWidth, &bi->bmiHeader.biHeight, ctx->video_size);
        |                                                           ^~~~~~~~~~~~~~~~~~~~~~~
        |                                                           |
        |                                                           LONG * {aka long int *}
  D:/workspace/FletchWindowsPR/build/build/src/FFmpeg/libavutil/parseutils.h:66:46: note: expected 'int *' but argument is of type 'LONG *' {aka 'long int *'}
     66 | int av_parse_video_size(int *width_ptr, int *height_ptr, const char *str);
        |                                         ~~~~~^~~~~~~~~~
  make: *** [/d/workspace/FletchWindowsPR/build/build/src/FFmpeg/common.mak:60: libavdevice/vfwcap.o] Error 1
```

Maybe work out the issues with ffnvcodec in another PR? It doesn't seem to be related to OpenCV

**Comment by aronhelser** [comment]
Yep, it was just an outstanding change I had, doesn't seem to be needed, so I removed it.

**Comment by aronhelser** [comment]
@daniel-riehm is the windows build still failing for some reason?

**Comment by aronhelser** [comment]
ping @daniel-riehm @chetnieter is out this week, can you merge?

**Pull request merged**
