### PR TITLE
Add OpenCV 4.2

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Add support for OpenCV 4.2 (see also #618). Make it the default version.

Note that this is not intended to be merged at this time, but is rather being submitted for CI to pick up and test.

### CODE REVIEW

**Comment by aaron-bray** [comment]
OpenCV is on 4.4
If we are going to update, should we update to the current latest?

**Comment by mwoehlke-kitware** [comment]
I went with 4.2 because that's what's available on Fedora. I suspect 4.4 is too new to be packaged many places yet, although also I expect 4.4 is compatible with 4.2 (whereas 4.x is *not* compatible with 3.x).

**Comment by dstoup** [comment]
Well, not surprising that it fails to build everywhere. It was a good test regardless to remind us of all the things in Fletch that depend on OpenCV. I'm ok with merging the update branch, we'll just need to update or patch a whole lot of packages before we can make it the default.

**Comment by mwoehlke-kitware** [comment]
Well, caffe at least seems to have the same issue as KWIVER; it's (ab)using the C API for no good reason. (Maybe 2.x didn't have the better C++ API yet? There have been further improvements in 4.x, but what I found patching KWIVER is a lot of the porting I had to do to make it work with 4.x *already* works with 3.x...)

**Comment by mleotta** [comment]
That's good news that supporting both OpenCV 3 and 4 is not difficult and mostly just involves using C++ APIs over C.

Yes, OpenCV was originally written in C only.  OpenCV 2 may have had some C++, but it was still very oriented around the original C API at that time.

**Pull request closed without merging**
