### PR TITLE
Help PDAL find dependencies on macos

### PR DESCRIPTION
**Pull request by mleotta**
Macos also needs help finding some of these libraries, not just WIN32.

### CODE REVIEW

**Comment by mleotta** [comment]
@dstoup @Cookt2 This change resolves by build issues on macOS in which PDAL was finding several system Frameworks over the Fletch-built libraries.  While this change fixes the problem, I also found similar issues in KWIVER and then came across a more general solution that we might want to also consider for Fletch.  If we
```
set(CMAKE_FIND_FRAMEWORK LAST)
```
before any `find_package` calls it will give Frameworks lower priority than the fletch libraries. 
See also https://github.com/Kitware/kwiver/pull/808

**Comment by mleotta** [comment]
Is the clang CI build still broken regardless of these changes?  Everything else is clear. Can we merge?

**Comment by dstoup** [comment]
> Is the clang CI build still broken regardless of these changes? Everything else is clear. Can we merge?

The Clang build is broken, yes. It won't build fletch correctly on the the CentOS 7 build of clang. I need to move the dashboard to a more modern distro to fix it. It can safely be ignored until then.

**Comment by mleotta** [comment]
This does fix my issues

**Pull request merged**
