### PR TITLE
Update the VXL version to master

### PR DESCRIPTION
**Pull request by dstoup**
Start using VXL master again since the FFmpeg issues appear fixed upstream.

### CODE REVIEW

**Comment by dstoup** [comment]
@mattdawkins

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by dstoup** [comment]
Jenkins test this please

**Comment by mattdawkins** [comment]
Did they keep the changed VXL input cmake variables? If so you might need:

https://github.com/Kitware/fletch/pull/479/files

Or cherry-picking the VXL_* changed flag commit

**Comment by mattdawkins** [comment]
When I go to build anything against this (or my) branch I get a:

/home/matt/Dev/viame/build/install/include/vxl/core/vil/vil_convert.h:83:36: fatal error: vcl_compiler_detection.h: No such file or directory
 #include <vcl_compiler_detection.h>

**Pull request closed without merging**
